# https://documentation.ubuntu.com/snapcraft/stable/reference/project-file/snapcraft-yaml/#reference-snapcraft-yaml
name: npmstat # you probably want to 'snapcraft register <name>'
title: NPM Package Stats and Info CLI
version: "0.0.1" # just for humans, typically '1.2+git' or '1.3.2'
license: MIT
# 79 char long summary
summary: Get NPM Package Stats and Info from the command line or as a Python module.
# You have a paragraph or two. Keep it under 100 words though we live in retardspace...
description: |
  Get NPM Package Stats and Info from the command line or as a Python module.

  To get started open your terminal and run: npmstat

  If you run into any issues or have any questions, support is available.

base: core24 # the base snap is the execution environment for this snap

grade: stable # must be 'stable' to release into candidate/stable channels
#grade: stable
confinement: strict # use 'strict' once you have the right plugs and slots
#confinement: strict

source-code: https://github.com/cssnr/npmstat
contact: https://cssnr.github.io/npmstat/support
website: https://cssnr.github.io/npmstat
issues: https://github.com/cssnr/npmstat/issues
donation: https://ko-fi.com/cssnr

icon: docs/assets/images/logo.svg

platforms:
  amd64:
  #arm64:

parts:
  npmstat:
    plugin: python
    source: .
    #source-type: git
    #source: https://github.com/cssnr/npmstat

apps:
  npmstat:
    command: bin/npmstat
    plugs:
      - network
      - home
      - dot-npmstat

plugs:
  dot-npmstat:
    interface: personal-files
    write:
      - $HOME/.cache/npmstat.sqlite
