name: "Main"

on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug"
        run: |
          echo ${{ github.workflow_ref }}

      - name: "Test Local Action"
        id: test
        uses: smashedr/test-action@master
        #with:
        #  token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Echo Outputs"
        run: |
          echo results: '${{ steps.test.outputs.results }}'
