name: "Build"

on:
  workflow_call:
    inputs:
      tags:
        description: "Extra Tags: comma,separated"
        type: string
  workflow_dispatch:
    inputs:
      tags:
        description: "Extra Tags: comma,separated"
      dev:
        description: "Development Build"
        type: boolean
        default: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write
      packages: write

    steps:
      - name: "Debug CTX github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Debug"
        continue-on-error: true
        run: |
          echo "inputs.dev: ${{ inputs.dev }}"
          echo "inputs.tags: ${{ inputs.tags }}"
          echo "github.ref_name: ${{ github.ref_name }}"

      - name: "Generate Docker Tags"
        id: tags
        uses: cssnr/docker-tags-action@v1
        with:
          images: "ghcr.io/${{ github.repository }}"
          tags: |
            ${{ inputs.dev == true && 'dev' || '' }}
            ${{ inputs.tags }}

      - name: "Debug Docker Tags"
        continue-on-error: true
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "tags: ${{ steps.tags.outputs.tags }}"
          echo "labels: ${{ steps.tags.outputs.labels }}"
          echo "annotations: ${{ steps.tags.outputs.annotations }}"
