name: "Build"

on:
  workflow_dispatch:
    inputs:
      build:
        description: "Run Build"
        type: boolean
        default: false
      tags:
        description: "Build Tag"
      deploy:
        description: "Run Deploy"
        type: boolean
        default: true
      tag:
        description: "Deploy Tag"
        default: "latest"
  release:
    types: [published]

env:
  traefik-host: badges.cssnr.com
  stack-file: docker-compose-swarm.yaml
  stack-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}
  version: ${{ inputs.tag || github.ref_name }} # TODO: Confirm this is not latest on release

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - uses: madhead/semver-utils@latest
        id: semver
        with:
          version: ${{ github.ref_name }}

      - name: "Debug Semver Utils"
        run: |
          echo "${{ steps.semver.outputs.release }}"
          echo "${{ steps.semver.outputs.major }}"
          echo "${{ steps.semver.outputs.minor }}"
          echo "${{ steps.semver.outputs.patch }}"
          echo "${{ steps.semver.outputs.build }}"

      - name: "Generate Version Tags"
        id: version
        uses: cssnr/update-version-tags-action@release
        with:
          prefix: ""
          #tags: ${{ inputs.tags }}
          dry_run: true
          release: true
          #tag: ${{ steps.semver.outputs.release }}
          #tag: 1.29.1-release.1

      - name: "Debug Version Tags"
        continue-on-error: true
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "steps.version.outputs.tags: ${{ steps.version.outputs.tags }}"

      - name: "Generate Docker Tags"
        id: tags
        uses: cssnr/docker-tags-action@v1
        with:
          images: "ghcr.io/${{ github.repository }}"
          tags: ${{ steps.version.outputs.tags }}

      - name: "Debug Docker Tags"
        continue-on-error: true
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "tags: ${{ steps.tags.outputs.tags }}"
          echo "labels: ${{ steps.tags.outputs.labels }}"
          echo "annotations: ${{ steps.tags.outputs.annotations }}"
