name: "Build"

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tags:
        description: "Extra Tags: comma,separated"
        required: false
      dev:
        description: "Development Build"
        type: boolean
        default: true

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write
      packages: write

    steps:
      - name: "Debug CTX github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Debug"
        continue-on-error: true
        run: |
          echo "inputs.dev: ${{ inputs.dev }}"
          echo "inputs.tags: ${{ inputs.tags }}"
          echo "github.ref_name: ${{ github.ref_name }}"
