name: "Check Build"

on:
  pull_request_target:

jobs:
  check-build:
    name: "Check Build"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: "Debug CTX github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Checkout Pull"
        uses: actions/checkout@v5
        with:
          ref: "${{ github.event.pull_request.merge_commit_sha }}"

      - name: "Debug"
        continue-on-error: true
        run: |
          echo "::group::ls"
          ls -lAh
          echo "::endgroup::"

          echo "::group::tree"
          tree .
          echo "::endgroup::"

      #- name: "Check Build Action"
      #  if: ${{ !cancelled() }}
      #  uses: cssnr/check-build-action@v1
