name: "Deploy"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Push"]
    types: [completed]

env:
  stack-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}
  stack-file: docker-compose-swarm.yaml
  traefik-host: badges.cssnr.com

jobs:
  dispatch:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'release') }}
    name: "Dispatch"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    environment:
      name: cssnr
      url: https://www.cssnr.com/

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Dump github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      #- name: "Dump github.event.workflow_run"
      #  continue-on-error: true
      #  env:
      #    GITHUB_CTX: ${{ toJSON(github.event.workflow_run) }}
      #  run: echo "$GITHUB_CTX"

      - name: "Debug Variables"
        continue-on-error: true
        run: |
          echo "VERSION: ${{ github.ref_name }}"
          echo "stack-name: ${{ env.stack-name }}"
          echo "stack-file: ${{ env.stack-file }}"
          echo "traefik-host: ${{ env.traefik-host }}"

      - name: "Debug"
        continue-on-error: true
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.ref_name : ${{ github.ref_name  }}
          echo github.event.workflow_run.conclusion - '${{ github.event.workflow_run.conclusion }}'
          echo github.event.workflow_run.event - '${{ github.event.workflow_run.event }}'

      #- name: "Debug Release"
      #  continue-on-error: true
      #  run: |
      #    echo steps.release.outputs.tag_name: ${{ steps.release.outputs.tag_name }}
      #    ls -lAh .
      #    ls -lAh dist/
