name: "Deploy"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version Tag"
        default: "latest"
        required: false
  workflow_run:
    workflows: ["Push", "Release", "Build"]
    types: [completed]

env:
  stack-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}
  stack-file: docker-compose-swarm.yaml
  traefik-host: badges.cssnr.com
  version: ${{ inputs.version || github.event.workflow_run.head_branch || github.ref_name }}

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    environment:
      name: cssnr
      url: https://www.cssnr.com/

    steps:
      - name: "Debug Event"
        continue-on-error: true
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "Debug Variables"
        continue-on-error: true
        run: |
          echo "VERSION: ${{ env.version == 'master' && 'latest' || env.version }}"
          echo "STACK_NAME: ${{ env.stack-name }}"
          echo "TRAEFIK_HOST: ${{ env.traefik-host }}"

      - name: "EXTRA Debug"
        continue-on-error: true
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.ref_name : ${{ github.ref_name  }}
          echo github.event.workflow_run.conclusion - '${{ github.event.workflow_run.conclusion }}'
          echo github.event.workflow_run.event - '${{ github.event.workflow_run.event }}'

      #- name: "Debug Release"
      #  continue-on-error: true
      #  run: |
      #    echo steps.release.outputs.tag_name: ${{ steps.release.outputs.tag_name }}
      #    ls -lAh .
      #    ls -lAh dist/
