name: "Deploy"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version Tag"
        default: "latest"
        required: false
  #workflow_run:
  #  workflows: ["Build"]
  #  types: [completed]

env:
  traefik-host: badges.cssnr.com
  stack-file: docker-compose-swarm.yaml
  stack-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}
  version: ${{ inputs.version || github.event.workflow_run.head_branch || github.ref_name }}

jobs:
  deploy:
    #if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    environment:
      name: cssnr
      url: https://www.cssnr.com/

    steps:
      - name: "Debug CTX github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Debug Variables"
        continue-on-error: true
        run: |
          echo "VERSION: ${{ env.version == 'master' && 'latest' || env.version }}"
          echo "STACK_NAME: ${{ env.stack-name }}"
          echo "TRAEFIK_HOST: ${{ env.traefik-host }}"

      - name: "Debug Environment"
        continue-on-error: true
        env:
          version: ${{ env.version == 'master' && 'latest' || env.version }}
        run: |
          echo "env.version: ${{ env.version }}"
          echo "ghcr.io/${{ github.repository }}:${{ env.version }}"
