name: "Deploy"

on:
  workflow_dispatch:
    inputs:
      folder:
        description: "Folder"
        required: true
      file:
        description: "File"
        required: true
        default: "docker-compose-swarm.yaml"
      env:
        description: "Env File"
        required: false

env:
  env-file: ${{ inputs.folder }}/${{ inputs.env }}

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    environment:
      name: portainer
      url: https://portainer-o-us-east-1.hosted-domains.com/

    steps:
      - name: "Debug CTX github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Debug Variables"
        continue-on-error: true
        run: |
          echo "inputs.folder: ${{ inputs.folder }}"
          echo "inputs.file: ${{ inputs.file }}"
          echo "inputs.env: ${{ inputs.env }}"
          echo "----------"
          echo "file: ${{ inputs.folder }}/${{ inputs.file }}"
          echo "name: ${{ inputs.env }}"
          echo "env_file: ${{ inputs.env == '' && '' || env.env-file }}"
