name: "Dispatch"

on:
  workflow_run:
    workflows:
      - "Push"
    types:
      - completed

jobs:
  dispatch:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "Dispatch"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Debug"
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.ref_name : ${{ github.ref_name  }}
          echo github.event.workflow_run - '${{ github.event.workflow_run }}'
          echo github.event.workflow_run.conclusion - '${{ github.event.workflow_run.conclusion }}'

      #- name: "Debug Release"
      #  run: |
      #    echo steps.release.outputs.tag_name: ${{ steps.release.outputs.tag_name }}
      #    ls -lAh .
      #    ls -lAh dist/
