name: "Dispatch"

on:
  workflow_dispatch:
    inputs:
      build:
        description: "Run Build"
        type: boolean
        default: true
      deploy:
        description: "Run Deploy"
        type: boolean
        default: true
      cleanup:
        description: "Run Cleanup"
        type: boolean
        default: true
      env:
        description: "Environment to Deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

env:
  build: ${{ github.event_name == 'push' && true || inputs.build }}
  deploy: ${{ github.event_name == 'push' && true || inputs.deploy }}

jobs:
  dispatch:
    name: "Dispatch"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      #- name: "Checkout"
      #  uses: actions/checkout@v4

      - name: "Debug"
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.ref_name : ${{ github.ref_name  }}

      - name: "Latest"
        id: latest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release=$(gh release list --exclude-pre-releases --exclude-drafts --limit 1 --json tagName)
          tag_name=$(echo "${release}" | jq -r '.[0].tagName')
          echo "tag=${tag_name}" >> "$GITHUB_OUTPUT"

      - name: "Debug Latest"
        run: |
          echo steps.latest.outputs.tag: ${{ steps.latest.outputs.tag }}

      - name: "Download Release"
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ steps.latest.outputs.tag }}

      - name: "List Files"
        run: |
          ls -lAh .
