name: "Push"

on:
  workflow_dispatch:
  push:

jobs:
  push:
    name: "Push"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Success"
        run: |
          echo github.event_name: ${{ github.event_name }}

      - name: "Random"
        id: random
        run: |
          exit $((RANDOM % 2))

      - name: "Always"
        if: ${{ always() }}
        run: |
          echo steps.random.outcome: ${{ steps.random.outcome }}
