name: "Extra"

on:
  workflow_dispatch:
  schedule:
    - cron: "24 2 * * 5"
  push:

jobs:
  extra:
    name: "Extra"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Test"
        id: test
        run: |
          #exit $((RANDOM % 2))
          exit 1

      - name: "Always"
        if: ${{ always() }}
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo steps.test.outcome: ${{ steps.test.outcome }}

      - name: "Schedule"
        if: ${{ always() && github.event_name == 'schedule' }}
        run: |
          echo steps.test.outcome: ${{ steps.test.outcome }}

      - name: "Discord Notification"
        uses: sarisia/actions-status-discord@v1
        if: ${{ always() && steps.test.outcome == 'failure' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

      - name: "Confirm Schedule Run"
        if: ${{ always() && github.event_name == 'schedule' && steps.test.outcome == 'failure' }}
        run: |
          echo yes
