name: "Extra"

on:
  workflow_dispatch:
  push:

jobs:
  extra:
    name: "Extra"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Success"
        run: |
          echo github.event_name: ${{ github.event_name }}

      - name: "Random"
        id: random
        run: |
          exit $((RANDOM % 2))

      - name: "Always"
        if: ${{ always() && github.event_name == 'push' && steps.random.outcome == 'failure' }}
        run: |
          echo steps.random.outcome: ${{ steps.random.outcome }}
