name: Call a reusable workflow

on:
  push:

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
    with:
      name: "artifact"
      path: ".github"
    #secrets:
    #  token: ${{ secrets.GITHUB_TOKEN }}

  debug:
    name: "Debug"
    runs-on: ubuntu-latest
    steps:
      - name: "Debug CTX github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Download Artifact"
        uses: actions/download-artifact@v5
        with:
          name: "artifact"

      - name: "Debug"
        run: |
          ls -lAh .
          echo "::group::tree"
          tree .
          echo "::endgroup::"
