name: "Homebrew"

on:
  workflow_dispatch:
    inputs:
      fail:
        description: "Fail Job"
        type: boolean
        default: false
      version:
        description: "Version to update."
        default: ""
      url:
        description: "URL to update."
        default: "https://github.com/cssnr/vitepress-plugin-contributors/releases/download/0.0.5/dist.zip"
      message:
        description: "Commit message."
        default: "Bump ralf to -99"
      repo:
        description: "Repository owner/name of the homebrew tap."
        default: "smashedr/homebrew-test"
      formula:
        description: "Formula file relative to the Formula directory."
        default: "toml-run.rb"
      branch:
        description: "Branch to Checkout and Push too."
        default: ""
      token:
        description: "Fine Grained or Personal Access Token with permissions contents: write"
        default: "1"
  #push:
  #  branches: ["**"]

jobs:
  homebrew:
    name: "Homebrew"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: "Set Formula File"
        env:
          path: homebrew-tap/Formula
        shell: bash
        run: |
          echo "inputs.version: ${{ inputs.version }}"
          echo "inputs.url: ${{ inputs.url }}"
          echo "inputs.message: ${{ inputs.message }}"
          echo "inputs.formula: ${{ inputs.formula }}"
          echo "inputs.branch: ${{ inputs.branch }}"

      - name: "Get Default Branch"
        id: branch
        env:
          GH_TOKEN: ${{ github.token }} # inputs.token
        shell: bash
        run: |
          if [ -n "${{ inputs.branch }}" ];then
            branch="${{ inputs.branch }}"
          else
            branch="$(gh repo view ${{ inputs.repo }} --json defaultBranchRef --jq .defaultBranchRef.name)"
          fi
          echo "branch: ${branch}"
          echo "default=${branch}" >> "$GITHUB_OUTPUT"

      - name: "Checkout Homebrew Tap"
        uses: actions/checkout@v6
        with:
          path: homebrew-tap
          persist-credentials: false
          ref: ${{ steps.branch.outputs.default }}
          repository: ${{ inputs.repo }}

      - name: "Set Formula File"
        env:
          path: homebrew-tap/Formula
        shell: bash
        run: |
          if [ -n "${{ inputs.formula }}" ];then
            if [ -f "${{ env.path }}/${{ inputs.formula }}" ];then
              echo "formula=${{ env.path }}/${{ inputs.formula }}" >> "$GITHUB_ENV"
            elif [ -f "${{ env.path }}/${{ inputs.formula }}.rb" ];then
              echo "formula=${{ env.path }}/${{ inputs.formula }}.rb" >> "$GITHUB_ENV"
            fi
          else
            echo "formula=${{ env.path }}/${GITHUB_REPOSITORY#*/}.rb" >> "$GITHUB_ENV"
          fi

      - name: "Verify Formula File"
        shell: bash
        run: |
          echo "formula: ${{ env.formula }}"
          if [ ! -f "${{ env.formula }}" ];then
            echo "::error::Not a File: ${{ env.formula }}"
            ls -lah homebrew-tap/Formula
            exit 1
          fi

      - name: "Update URL"
        if: ${{ inputs.url }}
        shell: bash
        run: |
          line=$(grep -n -m1 '^[[:space:]]*url ' "${{ env.formula }}" | cut -f1 -d:)
          echo "line: ${line}"
          sed -i "${line}"'s,.*,  url "${{ inputs.url }}",' "${{ env.formula }}"

      - name: "Update Version"
        if: ${{ inputs.version }}
        shell: bash
        run: |
          line=$(grep -n -m1 '^[[:space:]]*version ' "${{ env.formula }}" | cut -f1 -d:)
          echo "line: ${line}"
          sed -i "${line}"'s/.*/  version "${{ inputs.version }}"/' "${{ env.formula }}"

      - name: "Debug Formula"
        shell: bash
        run: |
          echo "::group::cat ${{ env.formula }}"
          cat -n "${{ env.formula }}"
          echo "::endgroup::"

      - name: "Job Summary"
        id: summary
        working-directory: homebrew-tap
        shell: bash
        run: |
          file="$(basename ${{ env.formula }})"
          echo "file: ${file}"

          if [ -n "${{ inputs.message }}" ];then
            message="${{ inputs.message }}" >> "$GITHUB_OUTPUT"
          elif [ -n "${{ inputs.version }}" ];then
            message="Bump ${file} to ${{ inputs.version }}" >> "$GITHUB_OUTPUT"
          else
            message="Bump ${file}" >> "$GITHUB_OUTPUT"
          fi

          echo "message: ${message}"
          echo "message=${message}" >> "$GITHUB_OUTPUT"

          diff="$(git diff -U0 Formula)"
          echo "::group::diff"
          echo "${diff}"
          echo "::endgroup::"

          md="Formula: \`Formula/${file}\`\n"
          md+="URL: \`${{ inputs.url || 'not updated' }}\`\n"
          md+="Version: \`${{ inputs.version || 'not updated' }}\`\n"
          md+="git diff:\n\`\`\`text\n${diff}\n\`\`\`\n"
          echo -e "${md}" >> "$GITHUB_STEP_SUMMARY"

      - name: "Commit and Push"
        working-directory: homebrew-tap
        shell: bash
        run: |
          echo "message: ${{ steps.summary.outputs.message }}"
          echo "name: github-actions[bot]"
          echo "email: 41898282+github-actions[bot]@users.noreply.github.com"

          #git config --local user.name "github-actions[bot]"
          #git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          #git commit -a -m "${{ steps.summary.outputs.message }}"
          #git remote set-url origin "https://${{ inputs.token }}@github.com/${{ inputs.repo }}"
          #git push -u origin ${{ steps.branch.outputs.default }}
