name: "Push"

on:
  workflow_dispatch:
    inputs:
      fail:
        description: "Fail Job"
        type: boolean
        default: false
      version:
        description: "Version Tag"
        type: string
  push:
    branches: ["**"]

env:
  version: ${{ github.event.workflow_run.head_branch || github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  push:
    name: "Push"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Debug event.json"
        continue-on-error: true
        run: cat "${GITHUB_EVENT_PATH}"
      - name: "Debug CTX github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"
      - name: "Debug Environment"
        continue-on-error: true
        run: env

      - name: "Debug"
        continue-on-error: true
        run: |
          echo github.repository: ${{ github.repository }}
          echo github.event_name: ${{ github.event_name }}
          echo github.ref_name: ${{ github.ref_name  }}
          echo inputs.fail: ${{ inputs.fail }}
          echo inputs.fail: ${{ inputs.fail }}
          echo inputs.version: ${{ inputs.version }}
          echo env.version: ${{ env.version }}

      # BEGIN CUSTOM

      - name: "Parse Summary"
        id: summary
        run: |
          text=$(cat notes.md | sed '/^#/Q')
          echo "${text}"

          echo "text<<EOF" >> "$GITHUB_OUTPUT"
          echo "$text" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: "Debug 1"
        env:
          text: ${{ steps.summary.outputs.text }}
        run: |
          echo "${text}"

      - name: "Translate Summary"
        id: translate
        uses: smashedr/openai-translate-action@master
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          text: ${{ steps.summary.outputs.text }}
          #file: text.txt  # or a file
          languages: "es-MX,fr"

      - name: "Debug Translation"
        continue-on-error: true
        env:
          items: ${{ steps.translate.outputs.items }}
          results: ${{ steps.translate.outputs.results }}
          spanish: ${{ steps.translate.outputs.es-MX }}
          french: ${{ steps.translate.outputs.fr }}
        run: |
          echo "input_tokens: ${{ steps.translate.outputs.input_tokens }}"
          echo "output_tokens: ${{ steps.translate.outputs.output_tokens }}"
          echo "total_tokens: ${{ steps.translate.outputs.total_tokens }}"
          echo "es-MX: ${spanish}"
          echo "fr: ${french}"
          echo "results: ${results}"
          echo "${items}" | jq

      - name: "Test 1"
        continue-on-error: true
        run: |
          echo "${{ fromJSON(steps.translate.outputs.items).es-mx }}"

      - name: "Test 2"
        continue-on-error: true
        run: |
          echo "${{ fromJSON(steps.translate.outputs.items).fr }}"

      # END CUSTOM

      ## Optional Fail Job for Debugging
      - name: "Fail"
        if: ${{ inputs.fail }}
        run: |
          exit 1
