name: "Push"

on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  push:
    name: "Push"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      #      - name: "Debug"
      #        continue-on-error: true
      #        run: |
      #          #/usr/bin/xcodebuild -version
      #          echo ${{ github.run_number }}
      #          echo ${{ github.run_number50 }}

      #      - name: "Debug event.json"
      #        run: |
      #          cat "${GITHUB_EVENT_PATH}"
      #
      #      - name: "Docker Test Action"
      #        uses: smashedr/docker-test-action@v1

      #- name: "Run Number"
      #  id: run
      #  run: |
      #    #exit $((RANDOM % 2))
      #    echo "number=$(echo $((50 + ${{ github.run_number }})))" >> "$GITHUB_OUTPUT"

      - name: "Debug"
        run: |
          pwd
          ls -lah .

      - name: "Anne O. Tate"
        if: ${{ !cancelled() }}
        run: |
          name=".github/workflows/test.yaml"
          path="$(readlink -f "${name}")"
          echo "path: ${path}"
          root=$(git rev-parse --show-toplevel)
          echo "root: ${root}"
          file="$(realpath --relative-to="${root}" ${path})"
          echo "file: ${file}"
          echo "::warning file=${file},line=55::You Fucked Up Chuck"

#
#
#- name: "Purge Cache Action"
#  uses: cssnr/cloudflare-purge-cache-action@v2
#  with:
#    domains: example.com,cssnr.com
#    dry_run: true
#    token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

#- name: "Test Summary"
#  run: |
#    ls -lAh .github/workflows
#
#    results="$(ls -lAh .github/workflows/* | awk '{print $9" - "$5}')"
#    markdown='```text\n'"${results}"'\n```'
#    echo -e "${markdown}"
#    echo -e "${markdown}" >> $GITHUB_STEP_SUMMARY
