name: "Push"

on:
  workflow_dispatch:
    inputs:
      fail:
        description: "Fail Job"
        required: false
        type: boolean
        default: false
  push:
    branches: ["**"]

env:
  version: ${{ github.event.workflow_run.head_branch || github.ref_name }}

jobs:
  push:
    name: "Push"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Debug event.json"
        continue-on-error: true
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "Dump object"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Debug"
        continue-on-error: true
        run: |
          echo github.repository: ${{ github.repository }}
          echo github.event_name: ${{ github.event_name }}
          echo github.ref_name : ${{ github.ref_name  }}
          echo inputs.fail : ${{ inputs.fail }}
          echo env.version : ${{ env.version }}

      # BEGIN CUSTOM

      - name: "Generate Version Tags"
        id: version
        uses: cssnr/update-version-tags-action@v1
        with:
          tag: 1.0.3
          dry_run: true
          prefix: ""

      - name: "Debug Version Tags"
        continue-on-error: true
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "steps.version.outputs.tags: ${{ steps.version.outputs.tags }}"

      # END CUSTOM

      ## Optioanl Fail Job for Debugging
      - name: "Fail"
        if: ${{ inputs.fail }}
        run: |
          exit 1
