name: "Push"

on:
  workflow_dispatch:
  push:

jobs:
  push:
    name: "Push"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug"
        run: |
          ls -lAh .

      - name: "Debug event.json"
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "Docker Test Action"
        uses: smashedr/docker-test-action@v1

      - name: "Test Summary"
        run: |
          ls -lAh .github/workflows
          results='```text\n\n'"$(ls -lAh .github/workflows)"'\n```'
          echo -e "${results}"
          echo "${results}" >> $GITHUB_STEP_SUMMARY
