name: "Push"

on:
  workflow_dispatch:
  push:

jobs:
  push:
    name: "Push"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug"
        run: |
          ls -lAh .

      - name: "Debug event.json"
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "Docker Test Action"
        uses: smashedr/docker-test-action@v1

      - name: "Test"
        id: test
        run: |
          #exit $((RANDOM % 2))
          exit 0
          echo "tag=WINNING" >> "$GITHUB_OUTPUT"

      - name: "Before ${{ steps.test.outputs.tag }}"
        run: |
          echo ${{ steps.test.outputs.tag }}

      - name: "Failure"
        if: ${{ failure() }}
        run: |
          echo YOU FUCKED UP CHUCK!

      #- name: "Purge Cache Action"
      #  uses: cssnr/cloudflare-purge-cache-action@v2
      #  with:
      #    domains: example.com,cssnr.com
      #    dry_run: true
      #    token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      #- name: "Test Summary"
      #  run: |
      #    ls -lAh .github/workflows
      #
      #    results="$(ls -lAh .github/workflows/* | awk '{print $9" - "$5}')"
      #    markdown='```text\n'"${results}"'\n```'
      #    echo -e "${markdown}"
      #    echo -e "${markdown}" >> $GITHUB_STEP_SUMMARY
