name: "Push"

on:
  workflow_dispatch:
    inputs:
      fail:
        description: "Fail Job"
        type: boolean
        default: false
      version:
        description: "Version Tag"
        type: string
  push:
    branches: ["**"]

env:
  version: ${{ github.event.workflow_run.head_branch || github.ref_name }}

jobs:
  push:
    name: "Push"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    env:
      ref_name: "1.0.2"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Debug event.json"
        continue-on-error: true
        run: cat "${GITHUB_EVENT_PATH}"

      - name: "Debug CTX github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Debug Environment"
        continue-on-error: true
        run: env

      - name: "Debug"
        continue-on-error: true
        run: |
          echo github.repository: ${{ github.repository }}
          echo github.event_name: ${{ github.event_name }}
          echo github.ref_name: ${{ github.ref_name  }}
          echo inputs.fail: ${{ inputs.fail }}
          echo inputs.fail: ${{ inputs.fail }}
          echo inputs.version: ${{ inputs.version }}
          echo env.version: ${{ env.version }}

      # BEGIN CUSTOM

      - name: "Test 1"
        continue-on-error: true
        run: |
          echo test

      - name: "Use a Fucking Name Retard"
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: Formula/toml-run.rb
          formula-path: .
          tag-name: ${{ env.ref_name }}
          download-url: "https://github.com/${{ github.repository }}/releases/download/${{ env.ref_name }}/toml_run-${{ env.ref_name }}.tar.gz"
          download-sha256: f94ef95267c2aee45c12121993b0a85cdd614c60a54e90542753226ed41d8b86

          homebrew-tap: "smashedr/homebrew-test"
          create-pullrequest: false
          create-branch: false
        env:
          # the personal access token should have "repo" & "workflow" scopes
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_PAT }}

      - name: "Test 2"
        continue-on-error: true
        run: |
          echo two

      # END CUSTOM

      ## Optioanl Fail Job for Debugging
      - name: "Fail"
        if: ${{ inputs.fail }}
        run: |
          exit 1
