name: "Push"

on:
  workflow_dispatch:
    inputs:
      fail:
        description: "Fail Job"
        type: boolean
        default: false
      version:
        description: "Version Tag"
        type: string
  push:
    branches: ["**"]

env:
  version: ${{ github.event.workflow_run.head_branch || github.ref_name }}

jobs:
  push:
    name: "Push"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Debug event.json"
        continue-on-error: true
        run: cat "${GITHUB_EVENT_PATH}"

      - name: "Debug CTX github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Debug Environment"
        continue-on-error: true
        run: env

      - name: "Debug"
        continue-on-error: true
        run: |
          echo github.repository: ${{ github.repository }}
          echo github.event_name: ${{ github.event_name }}
          echo github.ref_name: ${{ github.ref_name  }}
          echo inputs.fail: ${{ inputs.fail }}
          echo inputs.fail: ${{ inputs.fail }}
          echo inputs.version: ${{ inputs.version }}
          echo env.version: ${{ env.version }}

      # BEGIN CUSTOM

      - name: "Test 0"
        run: |
          cat -n "Formula/sharex-cli.rb"

      - name: "Test 1"
        continue-on-error: true
        env:
          url: "https://github.com/cssnr/vitepress-plugin-contributors/releases/download/0.0.5/dist.zip"
          formula: "Formula/sharex-cli.rb"
          line: 5
        run: |
          sed -i "${line}"'s,.*,  url "${{ env.url }}",' "${{ env.formula }}"

      - name: "Test 2"
        continue-on-error: true
        run: |
          cat -n "Formula/sharex-cli.rb"

      #- name: Get default branch
      #  id: get
      #  run: |
      #    resp=$(curl -s -H "Accept: application/vnd.github+json" \
      #      -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #      "https://api.github.com/repos/smashedr/homebrew-test")
      #    branch=$(echo "$resp" | jq -r .default_branch)
      #    echo "default_branch=$branch" >> $GITHUB_OUTPUT

      - name: "Get Default Branch"
        id: branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          branch=$(gh repo view smashedr/homebrew-test --json defaultBranchRef --jq .defaultBranchRef.name)
          echo "default=$branch" >> $GITHUB_OUTPUT

      - name: "Test 3"
        continue-on-error: true
        run: |
          echo ${{ steps.branch.outputs.default }}
          echo AI RETARDED

      # END CUSTOM

      ## Optional Fail Job for Debugging
      - name: "Fail"
        if: ${{ inputs.fail }}
        run: |
          exit 1
