name: "Release"

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Debug event.json"
        continue-on-error: true
        run: cat "${GITHUB_EVENT_PATH}"
      - name: "Debug CTX github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"
      - name: "Debug Environment"
        continue-on-error: true
        run: env
      - name: "Debug"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: |
          ls -lAh .

      - name: "Parse Summary 1"
        continue-on-error: true
        id: summary1
        env:
          RELEASE_BODY: ${{ github.event.release.body }}
        run: |
          text=$(echo "${RELEASE_BODY}" | sed '/^#/Q')
          echo "text<<EOF" >> $GITHUB_OUTPUT
          echo "text" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: "Echo Summary 1"
        continue-on-error: true
        env:
          OUTPUT: ${{ steps.summary1.outputs.text }}
        run: echo "${OUTPUT}"

      - name: "Parse Summary 2"
        continue-on-error: true
        id: summary2
        run: |
          body="$(jq -r .release.body "${GITHUB_EVENT_PATH}")"
          echo "::group::body"
          echo "${body}"
          echo "::endgroup::"

          text="$(printf '%s\n' "$body" | awk 'NF==0{exit} /^\-/')"
          echo "::group::text"
          echo "${text}"
          echo "::endgroup::"

          echo "text<<EOF" >> $GITHUB_OUTPUT
          echo "text" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: "Echo Summary 2"
        continue-on-error: true
        env:
          OUTPUT: ${{ steps.summary2.outputs.text }}
        run: echo "${OUTPUT}"
