name: "Release"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug event.json"
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "Docker Metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/${{ github.repository }}"
          #flavor: |
          #  latest=auto
          #  prefix=v,onlatest=false

      - name: "Echo Metadata"
        run: |
          echo "tags: ${{ steps.meta.outputs.tags }}"
          echo "labels: ${{ steps.meta.outputs.labels }}"
          echo "annotations: ${{ steps.meta.outputs.annotations }}"

      - name: "Update Version Tags"
        id: tags
        uses: cssnr/update-version-tags-action@master

      - name: "Echo Tags"
        run: |
          echo "tags: ${{ steps.tags.outputs.tags }}"

      - name: "Update Release Notes"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo tags: ${{ steps.tags.outputs.tags }}

          body=$(gh release view --json body --jq '.body')
          echo "body:"
          echo "${body}"

          head=$(echo "${body}" | awk "/## What's Changed/{exit} {print}")
          echo "head:"
          echo "${head}"

          tail=$(echo "${body}" | sed -n '/## What's Changed/,$p')
          echo "tail:"
          echo "${tail}"

      #- name: "Upload to Release"
      #  if: ${{ github.event_name == 'release' }}
      #  uses: svenstaro/upload-release-action@v2
      #  with:
      #    overwrite: true
      #    file_glob: true
      #    file: .github/workflows/*

      #- name: "VirusTotal"
      #  uses: cssnr/virustotal-action@master
      #  with:
      #    vt_api_key: ${{ secrets.VT_API_KEY }}
