name: "Release"

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Extra Tags: comma,separated"
        required: false
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug event.json"
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "Debug"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: |
          echo github.ref_name: ${{ github.ref_name }}
          echo inputs.tags: ${{ inputs.tags }}

      - name: "Generate Version Tags"
        id: version
        uses: cssnr/update-version-tags-action@v1
        with:
          tags: ${{ inputs.tags }}
          dry_run: true
          prefix: ""

      - name: "Debug Version Tags"
        continue-on-error: true
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "steps.version.outputs.tags: ${{ steps.version.outputs.tags }}"

      - name: "Generate Docker Tags"
        id: tags
        uses: smashedr/docker-tags-action@v1
        with:
          images: "ghcr.io/${{ github.repository }}"
          tags: ${{ steps.version.outputs.tags }}

      - name: "Debug Docker Tags"
        continue-on-error: true
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "tags: ${{ steps.tags.outputs.tags }}"
          echo "labels: ${{ steps.tags.outputs.labels }}"
          echo "annotations: ${{ steps.tags.outputs.annotations }}"

      - name: "Docker Metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/${{ github.repository }}"
          #flavor: |
          #  latest=auto
          #  prefix=v,onlatest=false
          tags: ${{ steps.version.outputs.tags }}

      - name: "Debug Docker Metadata"
        run: |
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "tags: ${{ steps.meta.outputs.tags }}"
          echo "labels: ${{ steps.meta.outputs.labels }}"
          echo "annotations: ${{ steps.meta.outputs.annotations }}"

      #- name: "Update Version Tags"
      #  id: tags
      #  uses: cssnr/update-version-tags-action@master
      #- name: "Echo Tags"
      #  run: |
      #    echo "tags: ${{ steps.tags.outputs.tags }}"
      #- name: "Update Release Notes Action"
      #  uses: smashedr/update-release-notes-action@master
      #  with:
      #    tags: "v1,v1.0"
      #    #delimiter: "--"
      #    #remove: true
      #    location: tail

      #- name: "Update Release Notes"
      #  env:
      #    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  run: |
      #    echo tags: ${{ steps.tags.outputs.tags }}
      #
      #    body=$(gh release view --json body --jq '.body')
      #    echo "body:"
      #    echo "${body}"
      #
      #    if [[ body == *"----"* ]];then
      #      head=$(echo "${body}" | awk "/----/{exit} {print}")
      #      tail=$(echo "${body}" | sed -n '/----/,$p')
      #    else
      #      head=""
      #      tail="${body}"
      #    fi
      #
      #    echo "head:"
      #    echo "${head}"
      #
      #    echo "tail:"
      #    echo "${tail}"

      #- name: "Upload to Release"
      #  if: ${{ github.event_name == 'release' }}
      #  uses: svenstaro/upload-release-action@v2
      #  with:
      #    overwrite: true
      #    #file_glob: true
      #    #file: .github/workflows/*
      #    file: README.md

      #- name: "VirusTotal"
      #  uses: cssnr/virustotal-action@updates
      #  with:
      #    vt_api_key: ${{ secrets.VT_API_KEY }}
      #    #release_heading: "### Scan Results"
      #    #collapsed: "true"
      #    file_name: "id"

      #- name: "Get release body"
      #  id: notes
      #  run: |
      #    body="$(jq -r .release.body "$GITHUB_EVENT_PATH")"
      #    summary="$(printf '%s\n' "$body" | awk 'NF==0{exit} /^\-/')"
      #    echo "summary<<EOF" >> $GITHUB_OUTPUT
      #    echo "$summary" >> $GITHUB_OUTPUT
      #    echo "EOF" >> $GITHUB_OUTPUT
      #
      #- name: "Use summary"
      #  run: echo "${{ steps.notes.outputs.summary }}"
      #
      #- name: "Generate Whats New"
      #  if: ${{ github.event_name == 'release' }}
      #  env:
      #    SUMMARY: ${{ steps.notes.outputs.summary != '' && steps.notes.outputs.summary || 'GitHub Actions' }}
      #  run: |
      #    echo "${{ env.SUMMARY }}"
      #    mkdir -p whatsNew
      #    echo "${{ steps.notes.outputs.summary }}" > whatsNew/whatsnew-en-US
      #    cat whatsNew/whatsnew-en-US
